arduino:
    sensors : 
        {
            BMP180T : "temperature",
            BMP180P : "pressure",
            DHT22T  : "temperature",
            DHT22H  : "humidity",
            DHT22HI : "heatIndex",
            BH1750  : "lux"
        }
    usedConnection: "usb"

    usb: {port : 'ttyACM0', baud : 57600}

database:
    name : 'weatherStation'
    units :
        {
            temperature : "FLOAT",
            pressure    : "FLOAT",
            humidity    : "FLOAT",
            heatIndex   : "FLOAT",
            lux         : "INTEGER"
        }

    used: "sqlite"
    sqlite: {path : "default"}
    mongo : {server: "localhost", port : 27017}

    historyDB:
        enable: yes
        name: "history"
        updateEvery : {d : 0, h : 0, m : 10, s : 0}

    # It can only be enabled if historyDB is enabled
    dailyHistoryDB:
        enable: yes
        name: "dailyHistory"

    currentData:
        enable: yes
        path: "default"
        name: "currentData.json"
        updateEvery: {d: 0, h: 0, m: 1, s: 0}