arduino:
    sensors : 
        {
            BMP180T : "temperature",
            BMP180P : "pressure",
            DHT22T  : "temperature",
            DHT22H  : "humidity",
            DHT22HI : "heatIndex",
            BH1750  : "lux"
        }

    usedConnection: "433mhz"
    usb:    {port : 'ttyACM0', baud : 57600}
    433mhz: {rxPin: 27, bps: 2000}

data:
    name : 'weatherStation'
    values :
        {
            temperature : "FLOAT",
            pressure    : "FLOAT",
            humidity    : "FLOAT",
            heatIndex   : "FLOAT",
            lux         : "INTEGER"
        }

    usedDB: "sqlite"
    sqlite: {path : "default"}
    mongo : {server: "localhost", port : 27017}

    history:
        enable: yes
        name: "history"
        updateEvery : {d : 0, h : 0, m : 2, s : 0}

    # It can only be enabled if history is enabled
    dailyHistory:
        enable: yes
        name: "dailyHistory"

    currentData:
        enable: yes
        path: "default"
        name: "currentData.json"

webserver:
    enable: yes
    host: '172.0.0.1'
    port: 5000
    charts:
        history:
            enable: yes
            name: 'history'
            height: 500
            panels:
                [
                    {
                        name : "Temperature",
                        type : "spline",
                        values : ["temperature","heatIndex"],
                        units : "C",
                        height: 23.5, #Percentage of the panel in the chart
                        offset: 0     #Offset of the panel in respect of the previous one
                    },
                    {
                        name : "Pressure",
                        type : "spline",
                        values : ["pressure"],
                        units : "Pa",
                        height: 23.5, #Percentage of the panel in the chart
                        offset: 2     #Offset of the panel in respect of the previous one
                    },
                    {
                        name : "Humidity",
                        type : "spline",
                        values : ["humidity"],
                        units : "%",
                        height: 23.5, #Percentage of the panel in the chart
                        offset: 2     #Offset of the panel in respect of the previous one
                    },
                    {
                        name : "Illuminance",
                        type : "spline",
                        values : ["lux"],
                        units : "Lux",
                        height: 23.5, #Percentage of the panel in the chart
                        offset: 2     #Offset of the panel in respect of the previous one
                    }
                ]

    liveData:
        enable: yes
        path: "default"
        updateEvery: {d: 0, h: 0, m: 1, s: 0}